on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
      - name: Build with Code Composer Studio
        uses: maus007/docker-run-action-fork@v1
        with:
          image: rossphorus/ccstudio-12-msp430:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            set -e
            eclipse -noSplash -data /tmp/workspace -application com.ti.ccstudio.apps.projectImport -ccs.location "/work/.test/test_examples"
            eclipse -noSplash -data /tmp/workspace -application com.ti.ccstudio.apps.projectBuild -ccs.projects "test_examples" -ccs.configuration "example_adc"
            eclipse -noSplash -data /tmp/workspace -application com.ti.ccstudio.apps.projectBuild -ccs.projects "test_examples" -ccs.configuration "example_blocking_i2c"
            eclipse -noSplash -data /tmp/workspace -application com.ti.ccstudio.apps.projectBuild -ccs.projects "test_examples" -ccs.configuration "example_blocking_spi"
            eclipse -noSplash -data /tmp/workspace -application com.ti.ccstudio.apps.projectBuild -ccs.projects "test_examples" -ccs.configuration "example_blocking_uart"
            eclipse -noSplash -data /tmp/workspace -application com.ti.ccstudio.apps.projectBuild -ccs.projects "test_examples" -ccs.configuration "example_debug_serial"
            eclipse -noSplash -data /tmp/workspace -application com.ti.ccstudio.apps.projectBuild -ccs.projects "test_examples" -ccs.configuration "example_gpio"
